language: node_js

node_js:
  - "6"

script:
  - npm run lint
  - npm test

after_success:
  - npm build

env:
  global:
    - BLUEMIX_ORG="CloudDevOps"
    - BLUEMIX_SPACE="Jobgate"
  matrix:

deploy:
  - deploy:
    provider: bluemixcloudfoundry
    skip_cleanup: true
    edge:
      source: adamkingit/dpl
      branch: master
    manifest: manifest-us-prod.yml
    username: $BLUEMIX_USER
    password: $BLUEMIX_PASSWORD
    region:   us
    organization: $BLUEMIX_ORG
    space: $BLUEMIX_SPACE
    on:
      branch: master
      
  - deploy:
    provider: bluemixcloudfoundry
    skip_cleanup: true
    edge:
      source: adamkingit/dpl
      branch: master
    manifest: manifest-us-stage.yml
    username: $BLUEMIX_USER
    password: $BLUEMIX_PASSWORD
    region:   us
    organization: $BLUEMIX_ORG
    space: $BLUEMIX_SPACE
    on:
      branch: stage
